Fix: peek panics
Cyfrin/aderyn pull request #371
Opened 2024-04-25 15:00 UTC by TilakMaddy

Sometimes for node properties `offset`, `len` can have values like `-1` 

That's why it's important we check the bounds before we return the string

2024-04-29 12:57 UTC, alexroan commented
Waiting for Hackathon submissions to conclude before addressing this PR 👍

2024-05-01 09:43 UTC, alexroan requested changes
Could you add tests to check for these negative values please @TilakMaddy ?

Any time we fix something that's breaking, we should introduce tests at the same time :)

2024-05-01 11:48 UTC, TilakMaddy commented
I made a mistake. I don't think it's because of negative values (because we are deserializing it to `usize`). It has to be something else. Let me re run this without the checks on https://github.com/smartcontractkit/ccip/tree/ccip-develop/contracts to find out what values they were (which causes index out of bounds panic)

2024-05-06 12:44 UTC, alexroan commented
@TilakMaddy is this still relevant ?

2024-05-06 12:53 UTC, TilakMaddy commented
> @TilakMaddy is this still relevant ?

Yes Alex, we should get this PR in because it's important to check that index lies within bounds before accessing array element at that index

2024-05-06 13:12 UTC, merged