Detect disable aderyn comments
Cyfrin/aderyn pull request #567
Opened 2024-06-25 12:44 UTC by TilakMaddy

Context 
https://github.com/Cyfrin/aderyn-vscode/issues/20

This PR brings in:
* Option 1
* Type 1 & 2

2024-06-25 13:56 UTC, TilakMaddy commented on tests/contract-playground/src/ConstantsLiterals.sol
>          multipleUseOfBytes32 = 0x8a1b3dbe6301650442bfa765d4de23775fc9a4ec4329ebb5995ec7f1e3777dc4;
Type 1

2024-06-25 13:56 UTC, TilakMaddy commented on tests/contract-playground/src/uniswap/UniswapV2Swapper.sol
> +        router1.swapETHForExactTokens(amountOut, path, to, block.timestamp); // aderyn-disable-line
Type 2

2024-06-25 13:57 UTC, TilakMaddy commented on reports/report.md
> -
Line targetted by Type 2 comment ignored

2024-06-25 13:57 UTC, TilakMaddy commented on reports/report.md
> -
Line targetted by Type 1 comment ignored

2024-06-26 08:55 UTC, alexroan reviewed
@TilakMaddy This looks good.

QQ: What was your rationale for processing the ignore statements in fscloc instead of using tools like `peek` and `peek_above`?

2024-06-28 15:43 UTC, TilakMaddy commented
> @TilakMaddy This looks good.
> 
> QQ: What was your rationale for processing the ignore statements in fscloc instead of using tools like `peek` and `peek_above`?

While we can work it out using `peek`/ `peek_over`, implementing Type 3 comment [https://github.com/Cyfrin/aderyn-vscode/issues/20#issuecomment-2184084795] would mean we will have a lot of edge cases to deal with. 

The **underlying** reason I feel is that `peek` methods are meant to give us hints to describe/discover something about a `node` written in English. (Almost like they are properties of the node)

Whereas `disable-next-line` is **not** descriptive of the node itself. It's a user preference for aderyn. So we need to be comment centric instead of node centric while approaching this issue (IMO)

Here, I used `fscloc` as a hook because we already get access to the tokenized descriptions (meaning we only have to do `string.contains` on the *Comment* tokens for `aderyn-disable-*` , unlike `peek` methods (which have to retokenize the snippet of the node's code)

2024-07-10 10:26 UTC, alexroan requested changes
Sweet. @TilakMaddy we should aim to get this in ASAP, but with a few minor DevEx changes:

1. This should function regardless of whether or not the `--skip-cloc` flag is set.
2. `aderyn-ignore-next-line` and `aderyn-ignore` instead

Once these two are resolved, we're good to go I think! :)

2024-07-16 03:26 UTC, TilakMaddy commented on reports/report.json
>            },
WHy have these changed ?

2024-07-16 03:31 UTC, TilakMaddy commented on reports/report.json
>            },
Ahh now I see, it's because I added the comments to ignore, which changes the offset of existing nodes. All cool !

2024-07-16 03:32 UTC, TilakMaddy commented
> Sweet. @TilakMaddy we should aim to get this in ASAP, but with a few minor DevEx changes:
> 
> 1. This should function regardless of whether or not the `--skip-cloc` flag is set.
> 2. `aderyn-ignore-next-line` and `aderyn-ignore` instead
> 
> Once these two are resolved, we're good to go I think! :)

DONE ✅

2024-07-16 17:13 UTC, alexroan approved these changes

2024-07-16 17:14 UTC, merged