Detector: State variable that could be declared constant
Cyfrin/aderyn pull request #672
Opened 2024-08-19 05:29 UTC by TilakMaddy

2024-08-28 09:44 UTC, alexroan requested changes
To fix:
1. A false negative
2. Report noise

2024-08-28 09:44 UTC, alexroan commented on reports/report.md
> +- Found in src/StateVariableCouldBeDeclaredConstant.sol [Line: 2](../tests/contract-playground/src/StateVariableCouldBeDeclaredConstant.sol#L2)
We should follow the advice that aderyn gives. We should avoid writing new contracts with known issues that are captured by other detectors, unless it's unavoidable.

* For example, giving the contract a specific pragma can avoid this open pragma issue.
* An example of an unavoidable one is "Unused State Variables".

2024-08-28 09:44 UTC, alexroan commented on tests/contract-playground/src/StateVariablesManipulation.sol
> +    IERC20 public h = IERC20(address(3)); // BAD - but not caught. False negative.
I've added a false negative here.

2024-09-02 07:06 UTC, TilakMaddy commented
@alexroan 

1. False negative addressed
2. Noise removed

2024-09-02 10:56 UTC, alexroan approved these changes

2024-09-02 10:56 UTC, merged