Fix: Don't allow empty issues with no instances
Cyfrin/aderyn pull request #681
Opened 2024-08-19 11:33 UTC by TilakMaddy

After running through ignore lines, if there are 0 issues, then don't include it in report

2024-08-28 09:51 UTC, alexroan requested changes

2024-08-28 09:51 UTC, alexroan commented on aderyn_core/src/lib.rs
> +            if issue.instances.is_empty() {
Test for this?

2024-08-29 06:48 UTC, TilakMaddy commented
Waiting for #704  to get in, so I can write higher quality tests

2024-08-29 15:54 UTC, TilakMaddy commented on reports/empty_report.md
Here !

2024-08-30 16:42 UTC, TilakMaddy commented on aderyn_core/src/lib.rs
> +            if issue.instances.is_empty() {
✅ DONE

2024-09-02 12:54 UTC, alexroan approved these changes

2024-09-02 12:58 UTC, merged