Fix: Send Ether No Checks (`msg.sender` ---> any address)
Cyfrin/aderyn pull request #703
Opened 2024-08-24 10:20 UTC by TilakMaddy

Previous logic:
Look for checks on msg.sender

Flaw:
We can't track data yet. So there are false positives when it comes to say, passing `_msgSender()` as an argument to a function that accepts it as a `address from` in the parameters and then has checks on that.

Mitigation
Changed the logic to be satisfied so long as there is a check on any address

2024-08-24 10:23 UTC, TilakMaddy commented on tests/contract-playground/src/Trump.sol
> +                }
On a side note, this _feels_ like a code smell but I don't why. What do you think this is doing ? :P

2024-08-30 17:25 UTC, alexroan requested changes

2024-08-30 17:25 UTC, alexroan commented on aderyn_core/src/detect/high/send_ether_no_checks.rs
>          }
@TilakMaddy can you please rewrite the title and description? They don't seem quite right.

2024-08-31 06:08 UTC, TilakMaddy commented on tests/contract-playground/src/Trump.sol
> +                }
Should we write a detector that checks for comparison operator used on `block.number` 🤔

2024-08-31 06:18 UTC, TilakMaddy commented on reports/report.md
Changed !

2024-09-02 14:17 UTC, merged